### ISSUE TITLE
Fatal error upon installation: IFNULL is MySQL only function

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_campaign#1]
Error reading from database

More information about this error
Attempting to install on PostgreSQL fails with:

Debug info: ERROR: function ifnull(bigint, integer) does not exist
LINE 1: SELECT (IFNULL(MAX(sortorder), 0) + 1) AS sortorder FROM m_u...
^
HINT: No function matches the given name and argument types. You might need to add explicit type casts.
SELECT (IFNULL(MAX(sortorder), 0) + 1) AS sortorder FROM m_user_info_category
[array (
)]
Error code: dmlreadexception
Stack trace:

    line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
    line 920 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 1671 of /lib/dml/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()
    line 37 of /local/campaign/db/install.php: call to moodle_database->get_record_sql()
    line 670 of /lib/upgradelib.php: call to xmldb_local_campaign_install()
    line 1922 of /lib/upgradelib.php: call to upgrade_plugins()
    line 713 of /admin/index.php: call to upgrade_noncore()

**Comment by Trolli07** [comment]
Hi,

Thank you for the quick review.

I changed it to "COUNT(*) + 1". 

Thank you!

Olivier
