### ISSUE TITLE
Better to be more strict on value type

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_campaign#2]
I can see that the submitted `?campaign=...` is later compared to the list of configured campaigns.

Still, it never looks good to see a code that accepts and stores submitted HTTP parameter without any sanitisation as in https://github.com/cbluesprl/moodle-local_campaign/blob/f73901e302de9b7efa75a6ee33789949c96f4a52/lib.php#L40

Let me encourage you to implement more strict PARAM type for allowed campaign codes, ideally something like `PARAM_ALPHUNUM` or `PARAM_ALPHANUMEXT` and apply that at the very beginning of input processing.

**Comment by Trolli07** [comment]
Hi,

Thank you for the quick review.

Excellent observation.
I use "optional_param('campaign', false, PARAM_ALPHANUM);" now

Thank you!

Olivier
