### ISSUE TITLE
Namespaced classes should not have name prefixes

### ISSUE THREAD

**Issue by mudrd8mz** [cbluesprl/moodle-local_campaign#3]
The class `classes/local_campaign_admin_setting_configtextarea.php` has been put into the `local_campaign` namespace.

As such, it should not have the "local_campaign_" prefix in the name. Also its name could be better self-descriptive such as `campaign_codes` or `admin_setting_campaigns`.

Refs:

* https://docs.moodle.org/dev/Automatic_class_loading
* https://docs.moodle.org/dev/Coding_style#Namespaces

**Comment by Trolli07** [comment]
Hi,

Thank you for the quick review.

I didn't know. It is fixed.

Thank you!

Olivier
